image: debian:latest

before_script:
  - apt-get clean
  - apt-get update -y
  - apt-get install -y curl git
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.0/install.sh | bash
  - source /root/.bashrc
  - nvm install "$(cat .node-version)"
  - npm install

stages:
#  - test
  - deploy

#test:
#  stage: test
#  script:
#    - npm test

deploy:
  stage: deploy
  script:
    - scripts/update-authors.sh
    - npm run ci-publish || true
  only:
    - master
