image: debian:latest

before_script:
  - npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
  - apt-get clean
  - apt-get update -y
  - apt-get install -y curl git
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.0/install.sh | bash
  - source /root/.bashrc
  - nvm install "$(cat .node-version)"
  - npm install

stages:
#  - test
  - build
  - deploy

#test:
#  stage: test
#  script:
#    - npm test

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - lib/

deploy:
  stage: deploy
  script:
    - scripts/update-authors.sh
    - npm publish --access public
  only:
    - master
  artifacts:
      paths:
        - lib/
